In [1]:
from faker import Faker
import random
import csv
import pandas as pd

fake = Faker()

# Define the number of records to be generated
num_records = 10000

# Define classes of activities
activities_categories = {
    'physical_activities': ["Hair Salon Visit "  ,"Manicure/Pedicure" , "Facial Treatment" ,  "Massage " , "Sauna  " ,"Running", "Swimming", "Cycling", "Hiking", "Yoga", "Gym Workout", "Walking the dog", "Horseback Riding", "Dancing", "Skiing", "Meditation Retreat " , "Spa Day  " ,
 "Snowboarding", "Ice Skating", "Roller Skating", "Basketball", "Baseball", "Rugby", "Bowling", "Tennis", "Soccer","Sightseeing ", "Rock Climbing ",  "Beach Volleyball", "Horse Riding " ],
    'artistic_activities': ["Antique Shopping","Reading", "Cooking", "Painting", "Photography", "Writing", "Knitting", "Sewing", "Drawing ", "Pottery","Playing a musical instrument",
"Movie Watching","Theater Visit","Museum Visit","Art Gallery Visit","Concert Attendance","Opera Attendance ","Ballet Attendance","Comedy Show Attendance",
"Magic Show Attendance","Circus Attendance","Cooking Class","Art Class","Music Class","Dance Class","Language Learning", "Singing ","Book Club Participation","Wine Tasting" , "Tea Ceremony" , "Coffee Tasting ",  "Meditation Retreat " , ],
    'night_activities': ["Stargazing","Hiking ","Walking the dog", "Movie Watching", "Potluck Dinner"  ],
    'outdoor_activities': ["Antique Shopping","Fashion Shopping "  ,"Running", "Picnicking ","Camping ","Sunbathing ","Beach Volleyball","Sandcastle Building ","Kite Flying","Sailing ","Whale Watching", "Spa Day  " ,
"Canoeing ","Rafting ","Archery ","Fencing ","Golfing ","Chess ","Card Games ","Board Games ","Video Games","Zoo Visit" ,"Aquarium Visit","Amusement Park Visit","Cycling", 
"Shopping ", "Sightseeing ", "Bird Watching ", "Barbecue" , "Fruit Picking", "Farming Activities"  , "Horse Riding " , "Charity Work " , "Volunteering Activities ", 
"Fishing ", "Kayaking", "Skiing ","Walking the dog","Horseback Riding", "Meditation Retreat " ],
    'water_activities': ["Hot Spring Bath",   "Sauna  " ,"Scuba Diving ","Snorkeling", "Swimming","Kayaking", "Surfing",  "Sailing" ,"Whale Watching", "Canoeing",  "Rafting" ],
    'sports_activities': ["Basketball" ,"Baseball" ,"Rugby" ,"Bowling" ,"Tennis" ,"Soccer", "Gym Workout ", "Dancing ","Fishing ","Surfing","Skiing ",
                          "Snowboarding ", "Beach Volleyball",  "Kite Flying", "Sailing" ,  "Scuba Diving ", "Rafting" , "Fencing" , "Golfing" ],
    'home_activities': ["Facial Treatment" ,  "Massage " , "Reading ", "Cooking ",  "Yoga ",  "Meditation ",  "Painting ",  "Gardening ",  "Knitting", "Farming Activities"  , "Potluck Dinner"  , "Hot Spring Bath",   
"Sewing","Chess ","Card Games ","Board Games ","Video Games", "Writing","Dancing ","Singing ", "Playing a musical instrument", "Drawing ", "Tea Ceremony" , "Baking " , "Barbecue"   ],
    'extreme_activities': ["Rock Climbing ",  "Kayaking","Snowboarding ", "Ice Skating",
"Surfing", "Skiing ", "Kite Flying",  "Scuba Diving ",  "Rafting" ,  "Archery" ]
}

# Define weather conditions
weather_conditions = ['Sunny', 'Rainy', 'Snowy', 'Cloudy', 'Windy']

# Define likes for each person
likes = {
    'John': 'physical_activities',
    'Jane': 'artistic_activities',
    'Doe': 'night_activities',
    'Alice': 'outdoor_activities',
    'Bob': 'water_activities',
    'Charlie': 'sports_activities',
    'Eve': 'home_activities',
    'Mallory': 'extreme_activities',
    # Add more people and their likes here
}

# Open the CSV file to write the generated data
with open('dataset_activities.csv', 'w', newline='') as csv_file:
    writer = csv.writer(csv_file)

    # Write the header of the CSV file
    writer.writerow(['Name', 'Likes', 'Activity', 'Local', 'Date', 'Hour', 'Weather'])

    # Generate activity records
    for _ in range(num_records):
        name = random.choice(list(likes.keys()))
        local = fake.city()
        date = fake.date_between(start_date='-30d', end_date='today')
        hour = fake.time_object().strftime('%H:%M')
        weather = random.choice(weather_conditions)

        # Choose activity based on time, place, weather and person's likes
        if int(hour.split(':')[0]) < 6 or int(hour.split(':')[0]) > 20:
            activity = random.choice(activities_categories['night_activities'])
        elif local in ['Beach City', 'Mountain Town']:  # Add more outdoor locations here
            if weather != 'Rainy':
                activity = random.choice(activities_categories['outdoor_activities'])
            else:
                activity = random.choice(activities_categories['home_activities'])
        else:
            activity = random.choice(activities_categories[likes.get(name)])

        # Write data to CSV file
        writer.writerow([name, likes.get(name), activity, local, date, hour, weather])

print("Dataset successfully generated!")

Dataset successfully generated!

In [2]:
Data=pd.read_csv("dataset_activities.csv",sep=",",header=0)
Data

,Name,Likes,Activity,Local,Date,Hour,Weather
0,Alice,outdoor_activities,Movie Watching,Campbellfort,2023-09-28,01:58,Sunny
1,Bob,water_activities,Hot Spring Bath,North Stephanieport,2023-10-13,08:05,Windy
2,Alice,outdoor_activities,Beach Volleyball,Tinafurt,2023-09-24,16:47,Rainy
3,Charlie,sports_activities,Kite Flying,West Renee,2023-09-27,16:14,Cloudy
4,Charlie,sports_activities,Beach Volleyball,Michaelton,2023-10-11,20:05,Windy
...,...,...,...,...,...,...,...
9995,Alice,outdoor_activities,Volunteering Activities,Janetmouth,2023-10-15,08:36,Cloudy
9996,Charlie,sports_activities,Basketball,Lake Brian,2023-09-28,18:40,Rainy
9997,Bob,water_activities,Sauna,East Diane,2023-09-24,10:40,Sunny
9998,Mallory,extreme_activities,Skiing,East Robertside,2023-10-05,10:22,Rainy
9999,John,physical_activities,Dancing,Hardingberg,2023-09-16,15:52,Snowy